project_id = "vpyrrctzuudgokhkucli"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[auth]
enable_email_confirmations = true
enable_email_autoconfirm = false
email_double_confirm_changes = true

[functions.booking-confirmation]
verify_jwt = true

[functions.booking-reminders]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.auth-confirmation]
verify_jwt = false