project_id = "vpyrrctzuudgokhkucli"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[functions.booking-reminders]
verify_jwt = false

[functions.test-email]
verify_jwt = false